[package]
distribution = "2201.8.0"
org = "ballerinax"
name = "salesforce"
version = "8.1.0"
export = ["salesforce", "salesforce.bulk", "salesforce.soap","salesforce.bulkv2", "salesforce.apex"]
license= ["Apache-2.0"]
authors = ["Ballerina"]
keywords = ["Sales & CRM/Customer Relationship Management", "Cost/Freemium"]
icon = "icon.png"
repository = "https://github.com/ballerina-platform/module-ballerinax-sfdc"

[build-options]
observabilityIncluded = true

[platform.java17]
graalvmCompatible = true

[[platform.java17.dependency]]
path = "../native/build/libs/salesforce-native-8.1.0-SNAPSHOT.jar"
groupId = "io.ballerinax"
artifactId = "salesforce"
version = "8.1.0-SNAPSHOT"

[[platform.java17.dependency]]
groupId = "com.opencsv"
artifactId = "opencsv"
version = "5.9"
path = "./lib/opencsv-5.9.jar"

[[platform.java17.dependency]]
groupId = "org.cometd.java"
artifactId = "bayeux-api"
version = "4.0.4"
path = "./lib/bayeux-api-4.0.4.jar"

[[platform.java17.dependency]]
groupId = "org.cometd.java"
artifactId = "cometd-java-client"
version = "4.0.4"
path = "./lib/cometd-java-client-4.0.4.jar"

[[platform.java17.dependency]]
groupId = "org.cometd.java"
artifactId = "cometd-java-common"
version = "4.0.4"
path = "./lib/cometd-java-common-4.0.4.jar"

[[platform.java17.dependency]]
groupId = "org.eclipse.jetty"
artifactId = "jetty-client"
version = "9.4.18.v20190429"
path = "./lib/jetty-client-9.4.18.v20190429.jar"

[[platform.java17.dependency]]
groupId = "org.eclipse.jetty"
artifactId = "jetty-http"
version = "9.4.18.v20190429"
path = "./lib/jetty-http-9.4.18.v20190429.jar"

[[platform.java17.dependency]]
groupId = "org.eclipse.jetty"
artifactId = "jetty-io"
version = "9.4.18.v20190429"
path = "./lib/jetty-io-9.4.18.v20190429.jar"

[[platform.java17.dependency]]
groupId = "org.eclipse.jetty"
artifactId = "jetty-util"
version = "9.4.18.v20190429"
path = "./lib/jetty-util-9.4.18.v20190429.jar"

[[platform.java17.dependency]]
groupId = "org.eclipse.jetty"
artifactId = "jetty-util-ajax"
version = "9.4.18.v20190429"
path = "./lib/jetty-util-ajax-9.4.18.v20190429.jar"

[[platform.java17.dependency]]
groupId = "org.json"
artifactId = "json"
version = "20210307"
path = "./lib/json-20210307.jar"

[[platform.java17.dependency]]
groupId = "com.fasterxml.jackson.core"
artifactId = "jackson-databind"
version = "2.9.10.8"
path = "./lib/jackson-databind-2.9.10.8.jar"

[[platform.java17.dependency]]
groupId = "com.fasterxml.jackson.core"
artifactId = "jackson-annotations"
version = "2.9.10"
path = "./lib/jackson-annotations-2.9.10.jar"

[[platform.java17.dependency]]
groupId = "com.fasterxml.jackson.core"
artifactId = "jackson-core"
version = "2.9.10"
path = "./lib/jackson-core-2.9.10.jar"
